export const GET_COUNTRIES = "GET_COUNTRIES";
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const FILTER_REGION = "FILTER_REGION";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY";
export const ORDER_NAMES = "ORDER_NAMES";
export const ORDER_POPULATION = "ORDER_POPULATION";